# Generated by Django 4.0.3 on 2022-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='std',
            field=models.CharField(choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], default='5', max_length=4),
        ),
    ]
