# Generated by Django 4.0.3 on 2022-05-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_api2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeCircle',
        ),
    ]
